#!/usr/bin/python

from ytmusicapi import YTMusic, OAuthCredentials
import json
import re
import sys

credsfile = "/home/ashish/.config/ytmusic-creds.json"
oauthfile = "/home/ashish/.config/ytmusic-oauth.json"
lkplylstid = "PL9cE5Kd6uzpgUN5jZDyX1RvU6wQRt4co3"
lkmusicdir = "/media/storage/Music"


def handleexception(funcname, e):
    print(f'Error: {funcname}() failed with the following error!')
    print(e)

def call(f, *args, **kwargs):
    try:
        return f(*args, **kwargs)
    except Exception as e:
        handleexception(f.__name__, e)
        sys.exit(1)


def getid(source):
    idpatterns = [
        re.compile('/watch\\?v=([0-9A-Za-z_-]{11})(?:&|$)'),
        re.compile('^([0-9A-Za-z_-]{11})$')
    ]
    for pattern in idpatterns:
        match = pattern.search(source)
        if match:
            return match.group(1)
    print(f'Error: unable to get ID from "{source}"!')
    sys.exit(1)

if len(sys.argv) != 2:
    print("Error: incorrect usage!")
    sys.exit(1)
ytid = getid(sys.argv[1])


with open(credsfile, 'r') as f: creds = json.load(f)["installed"]
ytmusic = call(
    YTMusic,
    oauthfile,
    oauth_credentials=OAuthCredentials(
        **{k: creds[k] for k in ("client_id", "client_secret")}
    )
)

song = call(ytmusic.get_song, ytid)
try:
    ytmusic.add_history_item(song)
except Exception as e:
    print("Error: couldn't add [{ytid}] to history!")
    print(e)
    sys.exit(1)
